repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: [--maxkb=50000]
    -   id: debug-statements
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: check-json
    -   id: check-symlinks
    -   id: check-toml
    -   id: detect-private-key

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
    -   id: ruff
        types_or: [python, pyi]
        args: [--fix]
    -   id: ruff-format
        types_or: [python, pyi]
